# Generated by Django 5.0 on 2024-01-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakashi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='email',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='msg',
            name='mobile',
            field=models.BigIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='msg',
            name='msg',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='msg',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
